name: Build, Lint and Test MaTech Software Website

on:
  push:
    branches:
      - main
      - "*"

env:
  NODE_VERSION: 20

jobs:
  build:
    name: Build MaTech Software Website
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm install

      - name: Build MaTech Software Website
        run: npm run build

  lint:
    name: Lint MaTech Software Website
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm install

      - name: Lint MaTech Software Website
        run: npm run lint
        continue-on-error: true
  test:
    name: Test MaTech Software Website
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm install

      - name: Test MaTech Software Website
        run: npm run test

  sonarcloud:
    name: Unittests + SonarCloud
    needs: build
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      # - name: Test and coverage
      #   working-directory: next
      #   run: npm run test:unit:coverage
      # - name: Check coverage output
      #   working-directory: next
      #   run: cat coverage/lcov.info
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
