name: Build and Deploy MaTech Software Website

on:
  push:
  pull_request:
    branches: "*"

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MaTech Software Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build MaTech Software Website
        run: npm run build
