name: Build, Lint, Test, Release and Deploy MaTech Software Website

on:
  push:
    branches:
      - main
      - "*"

env:
  NODE_VERSION: 18

jobs:
  build:
    name: Build MaTech Software Website
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm ci

      - name: Build MaTech Software Website
        run: npm run build

  lint:
    name: Lint MaTech Software Website
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm ci

      - name: Lint MaTech Software Website
        run: npm run lint
        continue-on-error: true
  test:
    name: Test MaTech Software Website
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm ci

      - name: Test MaTech Software Website
        run: npm run test

  # release:
  #   name: Tag and Release MaTech Software Website
  #   if: github.ref == 'refs/heads/main'
  #   needs: [build, test, lint]
  #   permissions: write-all
  #   runs-on: ubuntu-latest
  #   env:
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   timeout-minutes: 1
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Get Version from package.json
  #       id: version
  #       run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

  #     - name: Create Tag and Release
  #       run: gh release create v${{ env.VERSION }} -t "Release v${{ env.VERSION }}"

  deploy:
    name: Deploy MaTech Software Website
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm ci

      - name: Build MaTech Software Website
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./dist/*"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
