name: Deploy MaTech Software Website

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  build:
    name: Build MaTech Software Website
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm install

      - name: Build MaTech Software Website
        run: npm run build
  deploy:
    name: Deploy MaTech Software Website
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm install

      - name: Build MaTech Software Website
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./dist/*"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
