name: Deploy MaTech Software Website

on:
  push:
    branches:
      - 5-add-deployment

env:
  NODE_VERSION: 18

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build MaTech Software Website
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: ls
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: './dist/*'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          REMOTE_PORT: ${{ secrets.PORT }}
