name: Create Tag and Release MaTech Software Website on GitHub

on:
  push:
    branches:
      - dev

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
