name: Create Tag and Release MaTech Software Website on GitHub

on:
  push:
    branches:
      - dev

env:
  NODE_VERSION: 18

jobs:
  release:
    name: Tag and Release
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Dependencies Clean
        run: npm ci

      - name: Get Version from package.json
        id: version
        run: echo ::set-output name=version::$(jq -r .version package.json)

      - name: Create Tag and Release
        run: gh release create v${{ steps.version.outputs.version }} -t "Release v${{ steps.version.outputs.version }}" -n "Release notes for v${{ steps.version.outputs.version }}"
