name: Create Tag and Release MaTech Software Website on GitHub

on:
  push:
    branches:
      - dev

env:
  NODE_VERSION: 18

jobs:
  release:
    name: Tag and Release
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Version from package.json
        id: version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create Tag and Release
        run: gh release create v${{ env.VERSION }} -t "Release v${{ env.VERSION }}"
